from callbacks.before_agent_callback import check_if_agent_should_run
from callbacks.before_model_callback import alter_instructions
from callbacks.before_tool_callback import validate_tool_args

from callbacks.after_agent_callback import send_discount_coupon
from callbacks.after_model_callback import send_empty_stock_note
from callbacks.after_tool_callback import validate_tool_response